[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
dhat = "0.3.3"
regex = "1.11.1"
regex-automata = "0.4.9"

[profile.release]
debug = 1

[features]
dhat-heap = []
